---
- hosts: master
  tasks:
    - name: Kubeadm Config Pull
      shell: 
        sudo kubeadm config images pull

    - name: Init Cidr
      shell: 
        sudo kubeadm init --pod-network-cidr=10.0.0.0/16

    - name: Kubeconfig Mkdir
      shell: 
        mkdir -p $HOME/.kube

    - name: Kubeconfig Change
      shell: 
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config


    - name: Kubeconfig Chown
      shell:         
        sudo chown $(id -u):$(id -g) $HOME/.kube/config

    - name: Initilaze Calico for Kubernetes
      shell: |
        kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/tigera-operator.yaml
        curl https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/custom-resources.yaml -O
        sed -i 's/cidr: 192\.168\.0\.0\/16/cidr: 10.0.0.0\/16/g' custom-resources.yaml
        kubectl create -f custom-resources.yaml

    - name: KubeAdm Token
      shell:
        kubeadm token create --print-join-command
      register: kubeadm_token
       
    - set_fact:
        kubeadm_token_value: "{{ kubeadm_token }}"

    - debug:
        var: kubeadm_token_value
    